replicaCount: 1

namespace: minikube

service:
  port: 8087
  type: ClusterIP

ingress:
  enabled: false
  host: surveys.example.com
  certName: frontstage-cert

networkPolicy:
  egress: |
    - {}
  ingress: |
    - {}

resources:
  requests:
    memory: "256Mi"

email:
  secret:
    key: ONS_DUMMY_KEY