replicaCount: 1

env: "minikube"

service:
  port: 8087
  type: NodePort

secret:
  oauth_client_id: ons@ons.gov
  oauth_client_secret: password

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1028Mi"