replicaCount: 1

namespace: minikube
env: minikube

service:
  port: 8087
  type: ClusterIP

rollingUpdate:
    maxSurge: 1
    maxUnavailable:

image:
  name: eu.gcr.io/ons-rasrmbs-management
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  host: surveys.example.com
  certName: frontstage-cert

networkPolicy:
  egress: |
    - {}
  ingress: |
    - {}

resources:
  requests:
    memory: "256Mi"

email:
  secret:
    key: ONS_DUMMY_KEY