language: python
sudo: required
dist: trusty
python: '3.6'

cache:
  - pip

env:
   global:
     - PIPENV_IGNORE_VIRTUALENVS=1

services:
    - redis-server

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - make check
  - make lint
  - APP_SETTINGS=TestingConfig pipenv run pytest --cov=frontstage --cov-report xml --ignore=node_modules
  - pipenv run coverage report

after_success:
  - pipenv run codecov

branches:
  only:
    - master
