language: python
sudo: required
dist: trusty
python: '3.6'

# before_install:

cache:
  - pip

services:
    - redis-server

install:
  - pip install pipenv==8.3.2
  - pipenv install --dev --deploy

script:
  - make lint
  - APP_SETTINGS=TestingConfig pipenv run pytest --cov=frontstage --cov-report xml --ignore=node_modules
  - pipenv run coverage report

after_success:
  - pipenv run codecov

branches:
  only:
    - master
