language: python
sudo: required
dist: trusty
python: '3.5'

# before_install:

cache:
  - pip

env:
  - APP_SETTINGS=TestingConfig
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install codecov
  - pip install coverage

script:
  - pytest --cov=frontstage --cov-report xml --ignore=node_modules
  - coverage report

after_success:
  - codecov

branches:
  only:
    - master
