language: python
sudo: required
dist: trusty
python: '3.5'

# before_install:

cache:
  - pip
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install coverage

script:
  - coverage run ras-frontstage/tests/test_app.py
  - coverage report

# after_success:
    - codecov
    
branches:
  only:
    - feature/external-user-setup
