{{- if .Values.publicIP }}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: frontstage-backend-config
spec:
  securityPolicy:
    name: "ras-cloud-armor-policy"
  customRequestHeaders:
    X-Forwarded-Proto: https
  sessionAffinity: 
    affinityType: CLIENT_IP
{{- end }}
