{{- if not .Values.public }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontstage-backend-config
spec:
  securityPolicy:
    name: "ras-cloud-armor-policy"
  sessionAffinity: 
    affinityType: CLIENT_IP
{{- end }}
