apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontstage-backend-config
spec:
  securityPolicy:
    name: {{ .Values.armorPolicy }}
  sessionAffinity:
    affinityType: CLIENT_IP
  timeoutSec: {{ .Values.ingress.timeoutSec }}
