apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frontstage
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  refreshInterval: 1m
  data:
  - secretKey: email-secret-key
    remoteRef:
      key: frontstage
      property: email-secret-key
      version: latest
  - secretKey: email-salt
    remoteRef:
      key: frontstage
      property: email-salt
      version: latest

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: seft-collection-instrument-key
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  refreshInterval: 1m
  data:
  - secretKey: gpg-public-crypto-key
    remoteRef:
      key: seft-collection-instrument-key
      version: latest