apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: frontstage
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: frontstage
  data:
  - secretKey: email-secret-key
    remoteRef:
      key: frontstage
      property: email-salt
      version: latest
  - secretKey: email-salt
    remoteRef:
      key: frontstage
      property: email-salt
      version: latest

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: seft-collection-instrument-key
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: seft-collection-instrument-key
  data:
  - secretKey: gpg-public-crypto-key
    remoteRef:
      key: seft-collection-instrument-key
      version: latest
