apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: frontstage
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: frontstage
      name: email-secret-key
      version: latest
      property: email-secret-key
    - key: frontstage
      name: email-salt
      version: latest
      property: email-salt