{{- if .Values.ingress.enabled }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Values.ingress.frontendConfigName }}
spec:
  sslPolicy: {{ .Values.frontendConfig.sslPolicy }}
{{- end }}
