{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: frontstage-ip
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: {{ .Values.ingress.certNameSurveys }}
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: {{ .Values.service.port }}
{{- end }}
