{{- if .Values.ingress.enabled }}
{{- if not .Values.public }}
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: {{ .Values.ingress.certNameSurveys }}
spec:
  domains:
    - {{ .Values.ingress.surveysHost }}
{{- end }}
{{- end }}