apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  {{- if .Values.publicIP }}
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"{{ .Values.service.port }}":"frontstage-backend-config"}}'
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
