apiVersion: batch/v1
kind: Job
metadata:
  name: app-register-{{ .Values.pipelineMap }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      imagePullSecrets:
      - name: gcr-secret
      volumes:
      - name: pipelines
        configMap:
          name: {{ .Values.pipelineMap }}
      containers:
      - name: deploy
        image: eu.gcr.io/ons-rasrmbs-management/spin:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: pipelines
          mountPath: "/home/spin/pipelines"
          readOnly: true
        command: ["sh", "-cev"]
        args:
          - |
            spin applications --gate-endpoint $GATE_EP save --file /home/spin/pipelines/application.json
            spin pipeline --gate-endpoint $GATE_EP save --file /home/spin/pipelines/pipeline.json 
        env:
        - name: GATE_EP
          value: "http://$(SPIN_GATE_SERVICE_HOST):$(SPIN_GATE_SERVICE_PORT)"
      restartPolicy: Never
  backoffLimit: 2
