apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: ras-frontstage-ingress
    annotations:
        kubernetes.io/ingress.global-static-ip-name: "frontstage"
spec:
    backend:
        serviceName: ras-frontstage
        servicePort: 80
