{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{ .Values.networkPolicy.ingress | nindent 2 }}
  egress:
  {{ .Values.networkPolicy.egress | nindent 2 }}
{{- end }}