apiVersion: v1
kind: Secret
metadata:
  name: oauth-secret
type: Opaque
data:
  oauth-client-id: {{ .Values.secret.oauth_client_id | b64enc | quote }}
  oauth-client-secret: {{ .Values.secret.oauth_client_secret | b64enc | quote }}
