apiVersion: v1
kind: Secret
metadata:
  name: oauth-secret
type: Opaque
data:
  oauth-client-id: {{ .Values.secret.oauth-client-id | quote }}
  oauth-client-secret: {{ .Values.secret.oauth-client-secret | quote }}
